services:

  # Database postgres
  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - ./database/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=webapp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql

  # Django webapp
  app:
    container_name: webapp_container
    build: ./webapp
    volumes:
      - ./webapp:/webapp
    ports:
      - 8000:8000
    image: app:webapp
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  # # Redis
  # redis:
  #   container_name: redis
  #   image: redis:alpine
