# Generated by Django 4.2.5 on 2023-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[(1, "Instructor"), (2, "Learner"), (3, "Other"), (4, None)],
                default=4,
                max_length=200,
                null=True,
            ),
        ),
    ]
