# Generated by Django 4.2.5 on 2023-09-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dp",
            field=models.ImageField(
                default="/static/img/default_db.png", upload_to="images/post"
            ),
        ),
    ]
