# Generated by Django 4.2.5 on 2023-09-20 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_dp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dp",
        ),
    ]
