# Generated by Django 4.2.5 on 2023-09-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_user_dp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dp",
            field=models.ImageField(
                default="/static/img/default_dp.png", upload_to="dp/"
            ),
        ),
    ]
