# Generated by Django 4.2.5 on 2023-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_user_dp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dp",
            field=models.ImageField(blank=True, upload_to="dp/"),
        ),
    ]
